// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAefnjbFs75NU091WGeyRUyw57MNlYzlMg',
    appId: '1:99124191735:web:02135acb412cf835a40ef2',
    messagingSenderId: '99124191735',
    projectId: 'newsappjss',
    authDomain: 'newsappjss.firebaseapp.com',
    storageBucket: 'newsappjss.appspot.com',
    measurementId: 'G-N5X3192F3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkBAnbGTQsX4cUvGMKCRG-RvwvtRG-I5Y',
    appId: '1:99124191735:android:d49fa1898657a905a40ef2',
    messagingSenderId: '99124191735',
    projectId: 'newsappjss',
    storageBucket: 'newsappjss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZlU3AwK_Ir957Fd-7zO7SDwMwxEwXqio',
    appId: '1:99124191735:ios:0b2521b8e5000687a40ef2',
    messagingSenderId: '99124191735',
    projectId: 'newsappjss',
    storageBucket: 'newsappjss.appspot.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZlU3AwK_Ir957Fd-7zO7SDwMwxEwXqio',
    appId: '1:99124191735:ios:0b2521b8e5000687a40ef2',
    messagingSenderId: '99124191735',
    projectId: 'newsappjss',
    storageBucket: 'newsappjss.appspot.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAefnjbFs75NU091WGeyRUyw57MNlYzlMg',
    appId: '1:99124191735:web:5b6c5c3b3b589696a40ef2',
    messagingSenderId: '99124191735',
    projectId: 'newsappjss',
    authDomain: 'newsappjss.firebaseapp.com',
    storageBucket: 'newsappjss.appspot.com',
    measurementId: 'G-8EQEBB96H6',
  );
}
